### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ap0ught** [s-shin/linter-perl#13] opened 2015-07-20 19:19 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-perl](https://github.com/s-shin/linter-perl) package, v0.6.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/chris.mayfield/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:413

TypeError: Cannot read property 'length' of undefined
  at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Users/chris.mayfield/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:413:29)
  at exit (/Users/chris.mayfield/.atom/packages/linter-perl/lib/linter-perl.coffee:62:50)
  at triggerExitCallback (/Users/chris.mayfield/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Users/chris.mayfield/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  2x -2:07.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:57.7.0 editor:move-to-first-character-of-line (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:55.9.0 core:move-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:55.7.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:54.1.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:04.7.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:03.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -1:00.3.0 core:select-all (atom-text-editor.editor.vim-mode.insert-mode.is-focused.autocomplete-active)
     -0:59 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:57.9.0 core:move-to-top (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  5x -0:57.4.0 core:move-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:56.4.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:47.9.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.7.0 core:move-up (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.4.0 core:select-down (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:02.1.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-grep",
      "git-grep",
      "git-grep",
      "open-git-modified-files",
      "git-log",
      "git-plus",
      "tree-view-git-status",
      "merge-conflicts",
      "minimap"
    ]
  },
  "linter-perl": {}
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.5.3
linter, v1.2.4
linter-perl, v0.6.1
vim-mode, v0.55.0

# Dev
No dev packages
```

**Comment by s-shin** [comment] 2015-07-28 04:15
Thank you for reporting!
But the reported error is not reproduced yet in my environment.
I would like someone to give me more information about it.

**Comment by grigutis** [comment] 2015-08-02 20:43
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-perl](https://github.com/s-shin/linter-perl) package, v0.6.1


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:415

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:415:29)
    at exit (/Users/grigutis/.atom/packages/linter-perl/lib/linter-perl.coffee:89:80)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.3.0
linter-perl, v0.6.1

# Dev
No dev packages
```

**Comment by jrc-imente** [comment] 2015-11-09 16:02
I'm also in the same scenario. I try creating a new user on the system to check if it's something related with my user, and the problem persists. 
Also without importing a folder, only creating a perl file, and the crash is alway present.

**Atom Version**: 1.1.0
**System**: Ubuntu 15.10
**Thrown From**: [linter-perl](https://github.com/s-shin/linter-perl) package, v0.6.2

At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:432

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:432:29)
    at exit (/home/jrc/.atom/packages/linter-perl/lib/linter-perl.coffee:63:50)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.10.0
linter-perl, v0.6.2
linter-perlcritic, v0.3.0

# Dev
No dev packages

**Comment by jrc-imente** [comment] 2015-11-10 09:04
Problem resolved installing B::Lint in the system.

**Comment by s-shin** [comment] 2015-11-10 11:00
@jrc-imente Is your perl version perhaps above 5.18?
I wonder this issue is related to https://github.com/s-shin/linter-perl/issues/21.

**Comment by jrc-imente** [comment] 2015-11-10 11:12
@s-shin Yes, I'm using 5.20.2 as the perl version and is directly related with #21 error.

**Comment by s-shin** [comment] 2015-11-10 13:29
> Yes, I'm using 5.20.2 as the perl version

I see. I will have to look up B::Lint and show an alert if it is not installed.
Thanks, @jrc-imente.

---

This issue may be integrated to #21, but I leave it for a while.

**Comment by s-shin** [comment] 2015-11-12 16:40
https://github.com/s-shin/linter-perl/releases/tag/v0.7.0

**Comment by Arffeh** [comment] 2015-12-04 02:41
1. I've got perl 5.22
2. Same as above.
3. It worked for 10 minutes, then suddenly didn't.
4. still trying to figure out what tripped it up.
5. Possibly when I saved?
6. I like counting.


**Atom Version**: 1.2.4
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [linter-perl](https://github.com/s-shin/linter-perl) package, v0.7.1


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Arffeh\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:432

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (C:\Users\Arffeh\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:432:29)
    at exit (file:///C:/Users/Arffeh/.atom/packages/linter-perl/lib/linter-perl.coffee:68:50)
    at triggerExitCallback (C:\Users\Arffeh\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Arffeh\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
  2x -6:00.3.0 core:backspace (atom-text-editor.editor.is-focused)
 47x -0:34.4.0 core:move-up (atom-text-editor.editor.is-focused)
 13x -0:30 core:move-down (atom-text-editor.editor.is-focused)
     -0:27.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:26.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:19.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:18.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:16.5.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "Remote-FTP"
    ]
  },
  "linter-perl": {
    "executablePath": "C:\\Strawberry\\perl\\bin"
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.16
emmet-snippets-compatibility, v1.0.1
linter, v1.11.3
linter-perl, v0.7.1
remote-sync, v3.5.0

# Dev
No dev packages
```

**Comment by darutoko** [comment] 2015-12-07 19:39
[Enter steps to reproduce below:]

1. Download and install Atom
2. Install linter-perl
3. Open *.pl file

**Atom Version**: 1.2.4
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [linter-perl](https://github.com/s-shin/linter-perl) package, v0.7.1


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Alex\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:432

TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (C:\Users\Alex\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:432:29)
    at exit (file:///C:/Users/Alex/.atom/packages/linter-perl/lib/linter-perl.coffee:68:50)
    at triggerExitCallback (C:\Users\Alex\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Alex\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -1:16.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "linter-perl": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.11.3
linter-perl, v0.7.1

# Dev
No dev packages
```

**Comment by s-shin** [comment] 2015-12-09 14:31
OK, I reopen this issue.
In my small research, [the version of line-buffer is 7.1.3](https://github.com/atom/atom/blob/v1.2.4/package.json#L54), the error line may be [here](https://github.com/atom/text-buffer/blob/v7.1.3/src/text-buffer.coffee#L504), and so I'm doubting [`lineNum`](https://github.com/s-shin/linter-perl/blob/v0.7.1/lib/linter-perl.coffee#L68) would be invalid.
I will hotfix this by checking `lineNum`.

**Comment by pclinger** [comment] 2016-01-22 18:04
Got this error in Perl 5.16.3 (Windows), Atom 1.4.0, linter-perl 0.7.1

**Comment by s-shin** [comment] 2016-02-05 14:34
Perhaps fixed so closed.

**Closed by s-shin** 2016-02-05 14:34 UTC
Labels: bug, help wanted

**Comment by dudefellah** [comment] 2017-01-02 17:41
I've been noticing this issue on my end lately. It seems like it's been a while since it's been reported/discussed, but it seems to have started within the last few months for me.

Anyway, I suspected that this issue is actually coming up for me on blank buffers, causing calls for `buffer.lineLengthForRow(-1)` to come up with these error messages. Once I added checks in to make sure there are lines to check in the buffer, the problem seems to have gone away. I don't know enough about how this is supposed to work to know if that's a "good" solution to the problem or not, but it makes my life easier now regardless. Below are some details of my setup (with a small diff of my changes at the bottom). Hopefully this helps someone.

I have the following setup:

- Atom Version: 1.12.7
- Platform: Ubuntu 16.10
- Perl Version: v5.22.2

My config looks like this:

```javascript
"*":
  "atom-beautify":
    perl:
      beautify_on_save: true
    python:
      beautify_on_save: true
  core:
    automaticallyUpdate: false
    disabledPackages: [
      "linter-perl-check-syntax"
    ]
    telemetryConsent: "limited"
  editor:
    fontSize: 12
    invisibles: {}
    showInvisibles: true
    tabLength: 4
    tabType: "soft"
  "linter-perl":
    incPathsFromProjectRoot: [
      "."
      "lib"
    ]
  "linter-perl-check-syntax":
    incPathsFromProjectRoot: [
      "."
      "lib"
    ]
  perltidy:
    binary: "/usr/bin/perltidy"
  "tree-view": {}
  welcome:
    showOnStartup: false
```

```diff
diff --git a/lib/linter-perl.coffee b/lib/linter-perl.coffee
index 19f7fb4..c0ad6d0 100644
--- a/lib/linter-perl.coffee
+++ b/lib/linter-perl.coffee
@@ -61,7 +61,7 @@ module.exports = class LinterPerl
           [unused, message, filePath, lineNum] = m
           range = null
           buffer = textEditor.getBuffer()
-          if lineNum <= buffer.getLineCount()
+          if lineNum > 0 && lineNum <= buffer.getLineCount()
             range = [
               [lineNum-1, 0]
               [lineNum-1, buffer.lineLengthForRow(lineNum-1)]
```
